name: Docker

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:

  docker:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - name: Encontrar docker compose
        run: |
          find . -name "docker-compose*"